# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false
# Fabric Properties
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=0.1.0-alpha
maven_group=com.buildsense
archives_base_name=buildsense

# Dependencies
fabric_api_version=0.150.0+26.1.2